export enum EControlAction {
	InputNextCamera, // General Controls. These act as on foot controls but are technically separate
	InputLookLr, // In range -1 (left/up)...+1(right/down). Sign dependent on direction.
	InputLookUd,
	InputLookUpOnly, // In range 0...1. All directions positive.
	InputLookDownOnly,
	InputLookLeftOnly,
	InputLookRightOnly,
	InputCinematicSlowmo,
	InputScriptedFlyUd,
	InputScriptedFlyLr,
	InputScriptedFlyZup,
	InputScriptedFlyZdown,
	InputWeaponWheelUd, // These are for selecting a position in the weapon wheel
	InputWeaponWheelLr,
	InputWeaponWheelNext, // These switches between weapons in the same position of the weapon wheel
	InputWeaponWheelPrev,
	InputSelectNextWeapon, // These directly switch to the next weapon (used for a PC mouse).
	InputSelectPrevWeapon,
	InputSkipCutscene,
	InputCharacterWheel,
	InputMultiplayerInfo,
	InputSprint, // On Foot Controls
	InputJump,
	InputEnter,
	InputAttack,
	InputAim,
	InputLookBehind,
	InputPhone,
	InputSpecialAbility,
	InputSpecialAbilitySecondary,
	InputMoveLr, // In range -1 (left/up)...+1(right/down). Sign dependent on direction.
	InputMoveUd,
	InputMoveUpOnly, // In range 0...1. All directions positive.
	InputMoveDownOnly,
	InputMoveLeftOnly,
	InputMoveRightOnly,
	InputDuck,
	InputSelectWeapon,
	InputPickup,
	InputSniperZoom,
	InputSniperZoomInOnly,
	InputSniperZoomOutOnly,
	InputSniperZoomInSecondary,
	InputSniperZoomOutSecondary,
	InputCover,
	InputReload,
	InputTalk,
	InputDetonate,
	InputHudSpecial,
	InputArrest,
	InputAccurateAim,
	InputContext,
	InputContextSecondary,
	InputWeaponSpecial,
	InputWeaponSpecialTwo,
	InputDive,
	InputDropWeapon,
	InputDropAmmo,
	InputThrowGrenade,
	InputVehMoveLr, // In Vehicle Controls. In range -1 (left/up)...+1(right/down). Sign dependent on direction
	InputVehMoveUd,
	InputVehMoveUpOnly, // In range 0...1. All directions positive.
	InputVehMoveDownOnly,
	InputVehMoveLeftOnly,
	InputVehMoveRightOnly,
	InputVehSpecial,
	InputVehGunLr,
	InputVehGunUd,
	InputVehAim,
	InputVehAttack,
	InputVehAttack2,
	InputVehAccelerate,
	InputVehBrake,
	InputVehDuck,
	InputVehHeadlight,
	InputVehExit,
	InputVehHandbrake,
	InputVehHotwireLeft,
	InputVehHotwireRight,
	InputVehLookBehind,
	InputVehCinCam,
	InputVehNextRadio,
	InputVehPrevRadio,
	InputVehNextRadioTrack,
	InputVehPrevRadioTrack,
	InputVehRadioWheel,
	InputVehHorn,
	InputVehFlyThrottleUp,
	InputVehFlyThrottleDown,
	InputVehFlyYawLeft,
	InputVehFlyYawRight,
	InputVehPassengerAim,
	InputVehPassengerAttack,
	InputVehSpecialAbilityFranklin,
	InputVehStuntUd,
	InputVehCinematicUd,
	InputVehCinematicUpOnly,
	InputVehCinematicDownOnly,
	InputVehCinematicLr,
	InputVehSelectNextWeapon,
	InputVehSelectPrevWeapon,
	InputVehRoof,
	InputVehJump, // This is for bikes, try INPUT_VEH_CAR_JUMP
	InputVehGrapplingHook,
	InputVehShuffle,
	InputVehDropProjectile,
	InputVehMouseControlOverride,
	InputVehFlyRollLr, // In Aircraft specific Controls
	InputVehFlyRollLeftOnly,
	InputVehFlyRollRightOnly,
	InputVehFlyPitchUd,
	InputVehFlyPitchUpOnly,
	InputVehFlyPitchDownOnly,
	InputVehFlyUndercarriage,
	InputVehFlyAttack,
	InputVehFlySelectNextWeapon,
	InputVehFlySelectPrevWeapon,
	InputVehFlySelectTargetLeft,
	InputVehFlySelectTargetRight,
	InputVehFlyVerticalFlightMode,
	InputVehFlyDuck,
	InputVehFlyAttackCamera,
	InputVehFlyMouseControlOverride,
	InputVehSubTurnLr, // In Sub Controls
	InputVehSubTurnLeftOnly,
	InputVehSubTurnRightOnly,
	InputVehSubPitchUd,
	InputVehSubPitchUpOnly,
	InputVehSubPitchDownOnly,
	InputVehSubThrottleUp,
	InputVehSubThrottleDown,
	InputVehSubAscend,
	InputVehSubDescend,
	InputVehSubTurnHardLeft,
	InputVehSubTurnHardRight,
	InputVehSubMouseControlOverride,
	InputVehPushbikePedal, // On Pushbike Controls
	InputVehPushbikeSprint,
	InputVehPushbikeFrontBrake,
	InputVehPushbikeRearBrake,
	InputMeleeAttackLight, // Melee Combat Controls
	InputMeleeAttackHeavy,
	InputMeleeAttackAlternate,
	InputMeleeBlock,
	InputParachuteDeploy, // Parachute Controls
	InputParachuteDetach,
	InputParachuteTurnLr,
	InputParachuteTurnLeftOnly,
	InputParachuteTurnRightOnly,
	InputParachutePitchUd,
	InputParachutePitchUpOnly,
	InputParachutePitchDownOnly,
	InputParachuteBrakeLeft,
	InputParachuteBrakeRight,
	InputParachuteSmoke,
	InputParachutePrecisionLanding,
	InputMap, // PC Specific
	InputSelectWeaponUnarmed,
	InputSelectWeaponMelee,
	InputSelectWeaponHandgun,
	InputSelectWeaponShotgun,
	InputSelectWeaponSmg,
	InputSelectWeaponAutoRifle,
	InputSelectWeaponSniper,
	InputSelectWeaponHeavy,
	InputSelectWeaponSpecial,
	InputSelectCharacterMichael,
	InputSelectCharacterFranklin,
	InputSelectCharacterTrevor,
	InputSelectCharacterMultiplayer,
	InputSaveReplayClip,
	InputSpecialAbilityPc, // This is so you can have the same input for both on foot and in-car special abilities on PC
	InputCellphoneUp, // Cellphone Controls
	InputCellphoneDown,
	InputCellphoneLeft,
	InputCellphoneRight,
	InputCellphoneSelect,
	InputCellphoneCancel,
	InputCellphoneOption,
	InputCellphoneExtraOption,
	InputCellphoneScrollForward,
	InputCellphoneScrollBackward,
	InputCellphoneCameraFocusLock,
	InputCellphoneCameraGrid,
	InputCellphoneCameraSelfie,
	InputCellphoneCameraDof,
	InputCellphoneCameraExpression,
	InputFrontendDown, // Direct Controls. Used By Frontend ONLY.
	InputFrontendUp,
	InputFrontendLeft,
	InputFrontendRight,
	InputFrontendRdown,
	InputFrontendRup,
	InputFrontendRleft,
	InputFrontendRright,
	InputFrontendAxisX,
	InputFrontendAxisY,
	InputFrontendRightAxisX,
	InputFrontendRightAxisY,
	InputFrontendPause,
	InputFrontendPauseAlternate, // Alternate pause to get around conflict issues with Esc going back on PC.
	InputFrontendAccept,
	InputFrontendCancel,
	InputFrontendX,
	InputFrontendY,
	InputFrontendLb,
	InputFrontendRb,
	InputFrontendLt,
	InputFrontendRt,
	InputFrontendLs,
	InputFrontendRs,
	InputFrontendLeaderboard,
	InputFrontendSocialClub,
	InputFrontendSocialClubSecondary,
	InputFrontendDelete,
	InputFrontendEndscreenAccept,
	InputFrontendEndscreenExpand,
	InputFrontendSelect, // DP
	InputScriptLeftAxisX, // Remappable Script controls. For use in minigames and other scripts using a custom control scheme instead of direct pad controls and non-remappable front end controls. Left stick X analogue input. Values may be > 1 when using a mouse. Usually maps to movement
	InputScriptLeftAxisY, // Left stick Y analogue input. Values may be > 1 when using a mouse. Usually maps to movement
	InputScriptRightAxisX, // Right stick X analogue input. Values may be > 1 when using a mouse. Usually maps to look.
	InputScriptRightAxisY, // Right stick Y analogue input. Values may be > 1 when using a mouse. Usually maps to look.
	InputScriptRup, // PS3 = TRIANGLE, 360 = Y
	InputScriptRdown, // PS3 = X, 360 = A
	InputScriptRleft, // PS3 = SQUARE, 360 = X
	InputScriptRright, // PS3 = CIRCLE, 360 = B
	InputScriptLb, // Left shoulder button
	InputScriptRb, // Right shoulder button
	InputScriptLt, // Left shoulder trigger  - DIGITAL ONLY
	InputScriptRt, // Right shoulder trigger - DIGITAL ONLY
	InputScriptLs, // Left stick L3 button,
	InputScriptRs, // Right stick R3 button
	InputScriptPadUp, // D-Pad / Directional buttons up
	InputScriptPadDown, // D-Pad / Directional buttons down
	InputScriptPadLeft, // D-Pad / Directional buttons left
	InputScriptPadRight, // D-Pad / Directional buttons right
	InputScriptSelect, // Back button on 360, select on PS3
	InputCursorAccept, // Touch pad click or mouse button 1 click
	InputCursorCancel, // Mouse button 2 click
	InputCursorX, // The cursor X position in the range of 0...1.
	InputCursorY, // The cursor Y position in the range of 0...1.
	InputCursorScrollUp, // Scroll up, e.g. mouse wheel
	InputCursorScrollDown, // Scroll down, e.g. mouse wheel
	InputEnterCheatCode, // Brings up the cheat code input box.
	InputInteractionMenu, // Brings up the interaction menu.
	InputMpTextChatAll, // Brings up text chat box. Message sent to all players on a server.
	InputMpTextChatTeam, // Brings up text chat box. Message sent to all players on in the current team.
	InputMpTextChatFriends, // Brings up text chat box. Message sent to all friends on a server
	InputMpTextChatCrew, // Brings up text chat box. Message sent to all crew on a server
	InputPcPushToTalk, // Push to talk for VOIP
	InputCreatorLs, // Creator Left stick equivalent for functions like field of view, etc.
	InputCreatorRs, // Creator right stick equivalent for functions like field of view, etc.
	InputCreatorLt, // Creator left trigger equivalent for zooming.
	InputCreatorRt, // Creator right trigger equivalent for zooming.
	InputCreatorMenuToggle, // Creator menu toggle on/off for PC keyboard and mouse.
	InputCreatorAccept, // Creator accept/place items button.
	InputCreatorDelete, // Creator delete items button.
	InputAttack2, // Know one knows what this does!
	InputRappelJump,
	InputRappelLongJump,
	InputRappelSmashWindow,
	InputPrevWeapon, // This is temporarily mapped to the weapon wheel.
	InputNextWeapon, // This is temporarily mapped to the weapon wheel.
	InputMeleeAttack1, // This has been renamed to INPUT_MELEE_ATTACK_LIGHT. If this should be kept as it is, let me know thomas.randall@rockstarleeds.com
	InputMeleeAttack2, // This has been renamed to INPUT_MELEE_ATTACK_HEAVY. If this should be kept as it is, let me know thomas.randall@rockstarleeds.com
	InputWhistle, // This is mapped to nothing and is not used anywhere, it is added here so scripts work. If this should be kept let me know thomas.randall@rockstarleeds.com
	InputMoveLeft,
	InputMoveRight,
	InputMoveUp,
	InputMoveDown,
	InputLookLeft,
	InputLookRight,
	InputLookUp,
	InputLookDown,
	InputSniperZoomIn,
	InputSniperZoomOut,
	InputSniperZoomInAlternate,
	InputSniperZoomOutAlternate,
	InputVehMoveLeft,
	InputVehMoveRight,
	InputVehMoveUp,
	InputVehMoveDown,
	InputVehGunLeft,
	InputVehGunRight,
	InputVehGunUp,
	InputVehGunDown,
	InputVehLookLeft,
	InputVehLookRight,
	InputReplayStartStopRecording,
	InputReplayStartStopRecordingSecondary,
	InputScaledLookLr,
	InputScaledLookUd,
	InputScaledLookUpOnly,
	InputScaledLookDownOnly,
	InputScaledLookLeftOnly,
	InputScaledLookRightOnly,
	InputReplayMarkerDelete,
	InputReplayClipDelete,
	InputReplayPause,
	InputReplayRewind,
	InputReplayFfwd,
	InputReplayNewmarker,
	InputReplayRecord,
	InputReplayScreenshot,
	InputReplayHidehud,
	InputReplayStartpoint,
	InputReplayEndpoint,
	InputReplayAdvance,
	InputReplayBack,
	InputReplayTools,
	InputReplayRestart,
	InputReplayShowhotkey,
	InputReplayCyclemarkerleft,
	InputReplayCyclemarkerright,
	InputReplayFovincrease,
	InputReplayFovdecrease,
	InputReplayCameraup,
	InputReplayCameradown,
	InputReplaySave,
	InputReplayToggletime,
	InputReplayToggletips,
	InputReplayPreview,
	InputReplayToggleTimeline,
	InputReplayTimelinePickupClip,
	InputReplayTimelineDuplicateClip,
	InputReplayTimelinePlaceClip,
	InputReplayCtrl,
	InputReplayTimelineSave,
	InputReplayPreviewAudio,
	InputVehDriveLook,
	InputVehDriveLook2,
	InputVehFlyAttack2,
	InputRadioWheelUd,
	InputRadioWheelLr,
	InputVehSlowmoUp,
	InputVehSlowmoUpOnly,
	InputVehSlowmoDownOnly,
	InputVehHydraulicsControlToggle,
	InputVehHydraulicsControlLeft,
	InputVehHydraulicsControlRight,
	InputVehHydraulicsControlUp,
	InputVehHydraulicsControlDown,
	InputVehHydraulicsControlLr,
	InputVehHydraulicsControlUd,
	InputSwitchVisor,
	InputVehMeleeHold,
	InputVehMeleeLeft,
	InputVehMeleeRight,
	InputMapPoi,
	InputReplaySnapmaticPhoto,
	InputVehCarJump,
	InputVehRocketBoost,
	InputVehFlyBoost,
	InputVehParachute,
	InputVehBikeWings,
	InputVehFlyBombBay,
	InputVehFlyCounter,
	InputVehTransform,
	InputQuadLocoReverse,
	InputRespawnFaster,
	InputHudmarkerSelect, // INPUT_CNC_INTERACT_ATM,  temp removed because of ARCHIVED_SUMMER_CONTENT_ENABLED
	InputEatSnack,
	InputUseArmor,
	MaxInputs,
}