export enum EDecalRendersettingId {
	DecalRsidBloodSplatter = 1110,
	DecalRsidBloodDirectional = 1015,
	DecalRsidFootprintSand = 2020,
	DecalRsidBulletImpactMetalShotgun = 4202,
	DecalRsidGenericScorch = 4421,
	DecalRsidFloorScuff_1 = 7800,
	DecalRsidFloorScuff_2,
	DecalRsidFloorScuff_3,
	DecalRsidFloorScuff_4,
	DecalRsidLogoLostHollow = 9100,
	DecalRsidLogoLostGrey,
	DecalRsidLogoLostWhite,
	DecalRsidLogoCopsWhite,
	DecalRsidLogoVagosWhite,
	DecalRsidRaceLocateGround = 9106,
	DecalRsidRaceLocateAir,
	DecalRsidRaceLocateWater,
	DecalRsidTriathlonCycling = 9110,
	DecalRsidTriathlonRunning,
	DecalRsidTriathlonSwimming,
	DecalRsidHelipad = 9115,
	DecalRsidParachuteLanding,
	DecalRsidShadow,
	DecalRsidHalo,
	DecalRsidHaloPt,
	DecalRsidMpLocate_1,
	DecalRsidMpLocate_2,
	DecalRsidMpLocate_3,
	DecalRsidMpCreatorTrigger,
	DecalRsidOilPool = 9200,
}