export enum EDefaultDecisionMakers {
	DmPedGang = 65536,
	DmPedGroupJustFollow,
	DmPedCop,
	DmPedRandomNorm,
	DmPedRandomTough = 65539,
	DmPedRandomWeak = 65539,
	DmPedFireman,
	DmPedEmpty,
	DmPedIndoors = 65539,
	DmCombatGroupCrap = 65542, // Combat
	DmCombatGroupNormal,
	DmCombatGroupProfessional,
	DmCombatGroupHide,
	DmCombatNormal,
	DmCombatMissionCoward,
	DmCombatCopNorm = 65550,
	DmPedMissionEmptyCopy = 65554, // Decision makers that used to be loaded - can now be copied instead
	DmPedMissionNormCopy,
	DmPedMissionToughCopy,
	DmPedMissionWeakCopy,
	DmCombatEmptyCopy, // Combat
	DmCombatCowardCopy,
	DmCombatDefensiveCopy,
	DmCombatFierceCopy,
	DmCombatHideCopy,
	DmCombatCrapDefensiveCopy,
	DmCombatCrapNormalCopy,
	DmCombatCrapFierceCopy,
	DmCombatProfDefensiveCopy,
	DmCombatProfNormalCopy,
	DmCombatProfFierceCopy,
	DmCombatBossCopy,
}