export enum EDispatchType {
	DtPoliceAutomobile = 1,
	DtPoliceHelicopter,
	DtFireDepartment,
	DtSwatAutomobile,
	DtAmbulanceDepartment,
	DtPoliceRiders,
	DtPoliceVehicleRequest,
	DtPoliceRoadBlock,
	DtPoliceAutomobileWaitPulledOver,
	DtPoliceAutomobileWaitCruising,
	DtGangs,
	DtSwatHelicopter,
	DtPoliceBoat,
	DtArmyVehicle,
	DtBikerBackup,
	DtAssassins,
}