export enum EEIconType {
	IconTypeInvalid = -1,
	IconTypeHaircut,
	IconTypeTatto,
	IconTypeWeapon,
	IconTypeWeaponPlus,
	IconTypeArmour,
	IconTypeVehicle,
	IconTypeMask,
	IconTypeClothes,
	IconTypeKit,
	IconTypeMakeup,
	IconTypeBag,
	IconTypeBussinesProperty,
	IconTypeUsflag,
	IconTypeUsproperty,
	IconTypeAnchor,
	IconTypePlane,
	IconTypeHeli,
	IconTypeBike,
	IconTypeDiscount,
	IconTypeMystery,
	IconTypeArcade,
}