export enum EGameserverStates {
	GameserverInvalid,
	GameserverPendingAccessToken,
	WaitForStartSession,
	PendingCatalogVersion,
	GameserverPendingCatalog,
	GameserverCatalogComplete,
	GameserverPendingSessionStart,
	GameserverPendingSessionRestart,
	GameserverReady,
	GameserverFailedAccessToken,
	GameserverFailedCatalog,
	GameserverFailedSessionStart,
	GameserverFailedSessionRestart,
}