export enum EHelimode {
	HfAttainRequestedOrientation = 1,
	HfDontModifyOrientation,
	HfDontModifyPitch = 4,
	HfDontModifyThrottle = 8,
	HfDontModifyRoll = 16,
	HfLandOnArrival = 32,
	HfDontDoAvoidance = 64,
	HfStartEngineImmediately = 128,
	HfForceHeightMapAvoidance = 256,
	HfDontClampProbesToDestination = 512,
	HfEnableTimeslicingWhenPossible = 1024,
	HfCircleOppositeDirection = 2048,
	HfMaintainHeightAboveTerrain = 4096,
	HfIgnoreHiddenEntitiesDuringLand = 8192,
	HfDisableAllHeightMapAvoidance = 16384,
	HfNone = 0,
	HfHeightmaponlyavoidance = 320,
}