export enum EPedResetFlags {
	CpedResetFlagFallenDown = 0, // decides whether to ik rotate body to match ground angle
	CpedResetFlagDontRenderThisFrame = 1, // force ped to stop rendering this frame (for example - drive task can stop peds rendering inside buses)
	CpedResetFlagIsDrowning = 2,
	CpedResetFlagPedHitWallLastFrame = 3,
	CpedResetFlagUsingMobilePhone = 4,
	CpedResetFlagBlockMovementAnims = 5, // completely disable processing of on-foot movement anim blending for this frame
	CpedResetFlagZeroDesiredMoveBlendRatios = 6, // zero out all inputs to movement system this frame, causing ped to stop moving
	CpedResetFlagDontChangeMbrInSimpleMoveDoNothing = 7, // If this is set, then CTaskSimpleMoveDoNothing will not reset desired moveblendratio to zero this frame.
	CpedResetFlagFollowingRoute = 8, // whether this ped is following a route of some sort - used to let simplest goto task pull the ped back onto their current route segment
	CpedResetFlagTakingRouteSplineCorner = 9, // whether the ped is cornering via a spline curve, which will take them off their route linesegment
	CpedResetFlagWandering = 10,
	CpedResetFlagProcessPhysicsTasks = 11, // do we need to call process physics for (main) tasks this frame
	CpedResetFlagProcessPreRender2 = 12, // do we need to call ProcessPreRender2 for tasks
	CpedResetFlagSetLastMatrixDone = 13,
	CpedResetFlagFiringWeapon = 14, // set when ped fires any weapon, so script can check the flag
	CpedResetFlagSearchingForCover = 15, // Set if the ped is likely to be searching for cover, used by the navmesh to load coverpoints around interested peds
	CpedResetFlagKeepCoverPoint = 16, // Set if the ped wants to keep their current cover point this frame, otherwise it gets released
	CpedResetFlagIsClimbing = 17, // If the ped is climbing, shimmying or on a ladder.  Stops ProcessProbes() from happening.
	CpedResetFlagIsJumping = 18, // is the ped jumping.
	CpedResetFlagIsLanding = 19, // is landing after being in the air
	CpedResetFlagCullExtraFarAway = 20, // flag Ai can set to make ped get culled further away (used for roadblock cops, crimials...)
	CpedResetFlagDontActivateRagdollFromAnyPedImpactReset = 21,
	CpedResetFlagForceScriptControlledRagdoll = 22,
	CpedResetFlagTaskUseKinematicPhysics = 23, // For use by tasks - puts the ped into Kinematic physics mode. In this mode the ped will push other objects our of the way, but not be physically affected by them
	CpedResetFlagTemporarilyBlockWeaponSwitching = 24, // Stop weapon switch processing
	CpedResetFlagDoNotClampFootIk = 25, // Stop clamping the foot IK. Maybe the clamps should be parameters of the IK manager, but apparently that is to be refactored in future
	CpedResetFlagMoveBlendBFleeTaskRunning = 26, // TASK_SMART_FLEE, or TASK_COMPLEX_LEAVE_CAR_AND_FLEE
	CpedResetFlagIsAiming = 27, // TASK_GUN or TASK_USE_COVER
	CpedResetFlagMoveBlendBTaskComplexGunRunning = 28, // TASK_COMPLEX_GUN (only)
	CpedResetFlagMoveBlendBMeleeTaskRunning = 29, // TASK_COMPLEX_MELEE
	CpedResetFlagMoveBlendBCopSearchTaskRunning = 30, // TASK_COMPLEX_SEARCH_FOR_PED_ON_FOOT
	CpedResetFlagPatrollingInVehicle = 31, // ped is patrolling in a vehicle, likely meaning they are swat or police
	CpedResetFlagRaiseVelocityChangeLimit = 32,
	CpedResetFlagDimTargetReticule = 33,
	CpedResetFlagIsWalkingRoundPlayer = 34, // Whether this ped is walking around another ped (one frame latency)
	CpedResetFlagGestureAnimsAllowed = 35,
	CpedResetFlagVisemeAnimsBlocked = 36, // Blocks viseme anims from playing
	CpedResetFlagAmbientAnimsBlocked = 37, // Blocks new ambient idles from starting.
	CpedResetFlagKnockedToTheFloorByPlayer = 38,
	CpedResetFlagRandomisePointsDuringNavigation = 39,
	CpedResetFlagPrevent180SkidTurns = 40,
	CpedResetFlagIsOnAssistedMovementRoute = 41,
	CpedResetFlagApplyVelocityDirectly = 42, // Should we apply the velocity directly to the physics collider or go through the force solver?
	CpedResetFlagDisablePlayerLockon = 43,
	CpedResetFlagResetMoveGroupAfterRagdoll = 44, // If true, will reset the temp anim group when not ragdolling
	CpedResetFlagDisablePedConstraints = 45, // Allow the ped to rotate around freely
	CpedResetFlagDisablePlayerJumping = 46, // Disables player jumping if true. Reset in ResetPostPhysics, as it will be set via script
	CpedResetFlagDisablePlayerVaulting = 47, // Disables player vaulting/climbing if true.
	CpedResetFlagDisableAsleepImpulse = 48, // Disable the code that pushes peds which fall asleep in the air
	CpedResetFlagForcePostCameraAiUpdate = 49,
	CpedResetFlagForcePostCameraAnimUpdate = 50,
	CpedResetFlagEPostCameraAnimUpdateUseZeroTimestep = 51,
	CpedResetFlagCollideWithGlassRagdoll = 52,
	CpedResetFlagCollideWithGlassWeapon = 53,
	CpedResetFlagSyncDesiredHeadingToCurrentHeading = 54,
	CpedResetFlagAllowUpdateIfNoCollisionLoaded = 55,
	CpedResetFlagInternalWalkingRndPlayer = 56,
	CpedResetFlagPlacingCharge = 57, // Setting Bomb (firing weapon is set also)
	CpedResetFlagScriptDisableSecondaryAnimationTasks = 58, // Disable upper body animtion tasks such as shove ped and open door anims
	CpedResetFlagSearchingForClimb = 59,
	CpedResetFlagSearchingForDoors = 60,
	CpedResetFlagWanderingStoppedForOtherPed = 61,
	CpedResetFlagSupressGunfireEvents = 62,
	CpedResetFlagInfiniteStamina = 63, // Currently just for mounts, but could be expanded to anything with stamina
	CpedResetFlagBlockWeaponReactionsUnlessDead = 64, // Stops ragdoll and nm behaviors triggering from weapon damage unless the ped has died.
	CpedResetFlagForcePlayerFiring = 65,
	CpedResetFlagInCoverFacingLeft = 66, // set when exiting the cover state saying if we are facing left
	CpedResetFlagForcePeekFromCover = 67, // if set the ped will go into peeking if they are already in cover
	CpedResetFlagNotAllowedToChangeCrouchState = 68, // if set the ped will not be allowed to change their crouch state
	CpedResetFlagForcePedToStrafe = 69, // forces a ped to strafe
	CpedResetFlagForceMeleeStrafingAnims = 70, // forces a ped to use the melee strafing anims when strafing
	CpedResetFlagUseKinematicPhysics = 71, // To be used by scripts - puts the ped into Kinematic physics mode. In this mode the ped will push other objects our of the way, but not be physically affected by them
	CpedResetFlagClearLockonTarget = 72, // Clears the player's lockon target next frame
	CpedResetFlagCanPedSeeHatedPedBeingUsed = 73, // Activates can ped see hated ped generating events even when blocking of non-temp events is on
	CpedResetFlagInstantBlendToAim = 74, // Makes the ped performa an instant blend to aim if starting a gun task this frame
	CpedResetFlagForceImprovedIdleTurns = 75, // Forces the ped to use an improved idle turning system that should help him turn to face more quickly
	CpedResetFlagHitPedWithWeapon = 76, // set when damage is inflicted by this ped on another ped
	CpedResetFlagForcePedToUseScripCamHeading = 77, // forces a ped to the scripted camera heading instead of gameplay
	CpedResetFlagProcessProbesWhenExtractingZ = 78, // makes the capsule physics push the ped out of the ground even when extracting z
	CpedResetFlagKeepDesiredCoverPoint = 79, // should the ped keep their desired cover point this frame
	CpedResetFlagHasProcessedCornering = 80, // whether the ped has already processed slowing down for this corner
	CpedResetFlagStandingOnForkliftForks = 81, // Set when the ped standing capsule hits the forklift forks.
	CpedResetFlagAimWeaponReactionRunning = 82, // ped is running the reaction task this frame
	CpedResetFlagInContactWithFoliage = 83, // ped is in contact with GTA_FOLIAGE_TYPE bounds
	CpedResetFlagForceExplosionCollisions = 84, // ped will always collide with explosions, even when collision is off
	CpedResetFlagIgnoreTargetsCoverForLos = 85, // when checking LOS against targets this ped will ignore their cover (if the cover exists)
	CpedResetFlagBlockAnimatedWeaponReactions = 86, // Ped should not play animated damager reactions while this flag is set
	CpedResetFlagDisablePedCapsule = 87, // Removes the ped capsule from the physics simulation
	CpedResetFlagDisableCrouchWhileInCover = 88, // Force the crouch flag to return true while in cover.
	CpedResetFlagIncreasedAvoidanceRadius = 89, // Adds extra 2m onto the radius other peds use to avoid this ped during local steering.
	CpedResetFlagUnusedReplaceMe = 90,
	CpedResetFlagForceRunningSpeedForFragSmashing = 91, // Can be set by designers to force the ped to smash more easily through frags.
	CpedResetFlagEnableMoverAnimationWhileAttached = 92, // While flagged, any mover animation will be applied to the offset of the attachment.
	CpedResetFlagNoTimeDelayBeforeShot = 93, // While flagged, The time delay before a player can fire after aiming is 0
	CpedResetFlagSearchingForAutoVaultClimb = 94, // inform climb code we are doing an autovault
	CpedResetFlagExtraLongWeaponRange = 95, // Extends the range of a peds weapons to 250m
	CpedResetFlagForcePlayerToEnterVehicleThroughDirectDoorOnly = 96, // Forces the player to only use direct access when entering vehicles
	CpedResetFlagTaskCullExtraFarAway = 97, // Can be set by ai tasks on the main task tree to disable a ped getting cull from a vehicle.
	CpedResetFlagIsVaulting = 98, // Set the entire time CTaskVault is running.
	CpedResetFlagIsParachuting = 99, // Set the entire time CTaskParachute is running.
	CpedResetFlagSuppressSlowingForCorners = 100, // If set this will prevent the ped from slowing down to take corners this frame
	CpedResetFlagDisableProcessProbes = 101, // Disables processing of probes.
	CpedResetFlagDisablePlayerAutoVaulting = 102,
	CpedResetFlagDisableGaitReduction = 103,
	CpedResetFlagExitVehicleTaskFinishedThisFrame = 104,
	CpedResetFlagRequiresLegIk = 105,
	CpedResetFlagJayWalking = 106, // If set then the ped is jay walking and a vehicle is allowed to run him over.
	CpedResetFlagUseBulletPenetration = 107, // Ped will use bullet penetration code.
	CpedResetFlagForceAimAtHead = 108, // Force all attackers to target the head of this ped
	CpedResetFlagIsInStationaryScenario = 109, // In a scenario and not moving
	CpedResetFlagTemporarilyBlockWeaponEquipping = 110, // Stop weapon equipping
	CpedResetFlagCoverOutroRunning = 111, // TASK_AIM_GUN_FROM_COVER_OUTRO
	CpedResetFlagDisableSeeThroughChecksWhenTargeting = 112, // Any targeting LoS checks will fail if any materials with 'see through' materials found.
	CpedResetFlagPuttingOnHelmet = 113, // putting on helmet
	CpedResetFlagAllowPullingPedOntoRoute = 114, // allows goto task to apply heading in order to pull a ped back onto their route
	CpedResetFlagApplyAnimatedVelocityWhilstAttached = 115, // Allows attachment offsets to be updated from animated velocities
	CpedResetFlagAiCoverEntryRunning = 116, // TASK_ENTER_COVER
	CpedResetFlagResponseAfterScenarioPanic = 117, // The ped is entering threat response after panic exiting a scenario.
	CpedResetFlagIsNearDoor = 118, // Ped is near a non-vehicle door
	CpedResetFlagDisableTorsoSolver = 119,
	CpedResetFlagPanicInVehicle = 120,
	CpedResetFlagDisableDynamicCapsuleRadius = 121, // Turn off dynamic adjustments to ped capsules
	CpedResetFlagIsRappelling = 122, // Is currently in a rappel task
	CpedResetFlagSkipReactInReactAndFlee = 123, // When this ped goes to ThreatResponse, play the flee transition but not the reaction clip if fleeing.
	CpedResetFlagCannotBeTargeted = 124, // Will prevent this ped from being a part of any other peds target list
	CpedResetFlagIsFalling = 125, // Ped is in pure fall state (i.e. no parachuting, landing etc included
	CpedResetFlagForceInjuryAfterStunned = 126, // Forces this ped to the injured state after being stunned
	CpedResetFlagHurtThisFrame = 127, // The ped has entered the hurt state this frame
	CpedResetFlagBlockWeaponFire = 128, // Prevent the ped from shooting a weapon
	CpedResetFlagExpandPedCapsuleFromSkeleton = 129, // Set the ped capsule radius based on skeleton
	CpedResetFlagDisableWeaponLaserSight = 130, // Toggle the weapon laser sight off for this frame
	CpedResetFlagPedExitedVehicleThisFrame = 131, // Set when ped gets set out of vehicle
	CpedResetFlagSearchingForDropDown = 132, // Ped is seatching for drop down
	CpedResetFlagUseTighterTurnSettings = 133, // Ped should use tighter turn settings in human locomotion motion task
	CpedResetFlagDisableArmSolver = 134, // Disable the arm solver this frame
	CpedResetFlagDisableHeadSolver = 135,
	CpedResetFlagDisableLegSolver = 136,
	CpedResetFlagDisableTorsoReactSolver = 137,
	CpedResetFlagForcePreCameraAiUpdate = 138,
	CpedResetFlagTasksNeedProcessMoveSignalCalls = 139, // Set when peds require calls to ProcessMoveSignals(), for AI timeslicing to work with Move
	CpedResetFlagShootFromGround = 140,
	CpedResetFlagNoCollisionMovementMode = 141, // Set when a ped is moving in an area where collisions with fixed geometry are unlikely.  The ped's physics will not be forced to activate.
	CpedResetFlagIsNearLaddder = 142, // Ped is near top of a ladder
	CpedResetFlagSkipAimingIdleIntro = 143,
	CpedResetFlagIgnoredByAutoOpenDoors = 144, // Set this for a ped to be ignored by the auto opened doors when checking to see if the door should be opened.
	CpedResetFlagBlockIkWeaponReactions = 145, // Ped should not play Ik damager reactions while this flag is set
	CpedResetFlagFirstPhysicsUpdate = 146, // Ped was just created this frame
	CpedResetFlagSpawnedThisFrameByAmbientPopulation = 147, // Ped was spawned this frame
	CpedResetFlagDisableRootSlopeFixupSolver = 148,
	CpedResetFlagSuspendInitiatedMeleeActions = 149, // Temporarily suspend any melee actions this frame (does not include hit reactions). Use PCF_DisableMelee to turn it off completely
	CpedResetFlagSuppressInAirEvent = 150, // Prevents ped from getting the in air event the next frame
	CpedResetFlagAllowTasksIncompatibleWithMotion = 151, // If set, ped will skip CheckTasksAreCompatibleWithMotion
	CpedResetFlagIsEnteringOrExitingVehicle = 152, // TASK_ENTER_VEHICLE or TASK_EXIT_VEHICLE
	CpedResetFlagPlayerOnHorse = 153, // TASK_PLAYER_ON_HORSE
	CpedResetFlagHasGunTaskWithAimingState = 154, // Ped is running TASK_GUN and task's state is State_Aim
	CpedResetFlagSuppressLethalMeleeActions = 155, // This will suppress any melee action that is considered lethal (RA_IS_LETHAL, defined in action_table.meta)
	CpedResetFlagInstantBlendToAimFromScript = 156,
	CpedResetFlagIsStillOnBicycle = 157,
	CpedResetFlagIsSittingAndCycling = 158,
	CpedResetFlagIsStandingAndCycling = 159,
	CpedResetFlagIsDoingCoverAimOutro = 160,
	CpedResetFlagApplyCoverWeaponBlockingOffsets = 161,
	CpedResetFlagIsInLowCover = 162,
	CpedResetFlagAmbientIdleAndBaseAnimsBlocked = 163, // Blocks ambient idles and base animations from playing.
	CpedResetFlagUseAlternativeWhenBlock = 164, // If set, ped will use alternative aiming/firing anims
	CpedResetFlagForceLowLodWaterCheck = 165, // If set, the ped will always force probe for being in water when in low LOD mode.
	CpedResetFlagMakeHeadInvisible = 166, // If set, scale the head of the ped to 0.001
	CpedResetFlagNoAutoRunWhenFiring = 167, // Don't auto run when NoAutoRunWhenFiring is set.
	CpedResetFlagPermitEventDuringScenarioExit = 168, // Ignore certain aspects (FOV checks, etc) of AffectsPedCore() on some events while the ped is playing a scenario exit.
	CpedResetFlagDisableSteeringAroundVehicles = 169, // Enables/disables the low-level steering behaviour around vehicles
	CpedResetFlagDisableSteeringAroundPeds = 170, // Enables/disables the low-level steering behaviour around peds
	CpedResetFlagDisableSteeringAroundObjects = 171, // Enables/disables the low-level steering behaviour around objects
	CpedResetFlagDisableSteeringAroundNavMeshEdges = 172, // Enables/disables the low-level steering behaviour around nav mesh edges
	CpedResetFlagWantsToEnterVehicleFromCover = 173,
	CpedResetFlagWantsToEnterCover = 174,
	CpedResetFlagWantsToEnterVehicleFromAiming = 175,
	CpedResetFlagCapsuleBeingPushedByVehicle = 176,
	CpedResetFlagDisableTakeOffParachutePack = 177,
	CpedResetFlagIsCallingPolice = 178,
	CpedResetFlagForceCombatTaunt = 179, // Forces a combat taunt for peds using the insult special ability.
	CpedResetFlagIgnoreCombatTaunts = 180,
	CpedResetFlagSkipAiUpdateProcessControl = 181, // True if we've already run this ped's AI and can skip it from within ProcessControl
	CpedResetFlagOverridePhysics = 182, // A reset flag that disables collision and gravity on the ped and drives entity positions and rotations directly, rather than going through the physics update.
	CpedResetFlagWasPhysicsOverridden = 183, // True if physics was overriden during the last update.
	CpedResetFlagBlockWeaponHoldingAnims = 184, // Block any onfoot weapon holding anims.
	CpedResetFlagDisableMoveTaskHeadingAdjustments = 185, // True if the ped's movement task should not adjust the heading of the ped.
	CpedResetFlagDisableBodyLookSolver = 186,
	CpedResetFlagPreventAllMeleeTakedowns = 187, // Will temporarily prevent any takedown from being performed on this ped
	CpedResetFlagPreventFailedMeleeTakedowns = 188, // Will temporarily prevent any failed takedowns from being performed on this ped
	CpedResetFlagIsPedalling = 189,
	CpedResetFlagUseTighterAvoidanceSettings = 190, // Ped should use tighter avoidance settings in navigation task
	CpedResetFlagIsHigherPriorityClipControllingPed = 191, // True if the active task on the main task tree is taking responsibility for the mover track
	CpedResetFlagVehicleCrushingRagdoll = 192, // Set to true if a vehicle is pressing downward on the ragdoll
	CpedResetFlagOnActivationUpdate = 193, // Ped was just activated this frame
	CpedResetFlagForceMotionStateLeaveDesiredMbr = 194, // Set this to disable setting the desired move blendratio when forcing the motion state. Usefull for forcing a flee start, etc
	CpedResetFlagDisableDropDowns = 195, // Disable drop downs for this ped
	CpedResetFlagInContactWithBigFoliage = 196, // ped is in contact with GTA_FOLIAGE_TYPE bounds that are large and the player can be hidden
	CpedResetFlagDisableTakeOffScubaGear = 197,
	CpedResetFlagDisableCellphoneAnimations = 198, // tells taskmobile phone to Blends out move network and prevents it from blending in
	CpedResetFlagIsExitingVehicle = 199, // TASK_EXIT_VEHICLE
	CpedResetFlagDisableActionMode = 200, // Disables combat anims for ped
	CpedResetFlagEquippedWeaponChanged = 201, // Equipped weapon changed this frame
	CpedResetFlagTouchingOverhang = 202, // Some part appears to be contrained downwards
	CpedResetFlagTooSteepForPlayer = 203, // We're standing on something flagged too steep for the player to stand on
	CpedResetFlagBlockSecondaryAnim = 204, // Block any secondary scripted task animations playing on this ped
	CpedResetFlagIsInCombat = 205, // This ped is running the combat task
	CpedResetFlagUseHeadOrientationForPerception = 206, // Will use the ped's head orientation for perception tests
	CpedResetFlagIsDoingDriveby = 207, // This ped is running a driveby gun or projectile task
	CpedResetFlagIsEnteringCover = 208, // This ped is running a cover entry task
	CpedResetFlagForceMovementScannerCheck = 209, // Set to make CStaticMovementScanner
	CpedResetFlagDisableJumpRagdollOnCollision = 210, // If true, the player will no longer auto-ragdoll when colliding with objects, peds, etc. while jumping
	CpedResetFlagIsBeingMeleeHomedByPlayer = 211, // Set on the target ped in melee if the player is homing towards them
	CpedResetFlagShouldLaunchBicycleThisFrame = 212, // This ped should launch the bicycle this frame
	CpedResetFlagCanDoBicycleWheelie = 213, // This ped can do a bicycle wheelie
	CpedResetFlagForceProcessPhysicsUpdateEachSimStep = 214, // If true, ProcessPhysics() will execute completely for each physics simulation step
	CpedResetFlagDisablePedCapsuleMapCollision = 215, // Disables collision between the ped capsule and the map (usefull in cases where the entity position is being tightly controlled outside of physics, e.g. by an animation)
	CpedResetFlagDisableSeatShuffleDueToInjuredDriver = 216, // If true, motion in vehicle task won't shuffle to the driver seat just because the driver is injured
	CpedResetFlagDisableParachuting = 217,
	CpedResetFlagProcessPostMovement = 218, // do we need to call ProcessPostMovement for tasks
	CpedResetFlagProcessPostCamera = 219, // do we need to call ProcessPostCamera for tasks
	CpedResetFlagProcessPostPreRender = 220, // do we need to call ProcessPostPreRender for tasks
	CpedResetFlagPreventBicycleFromLeaningOver = 221,
	CpedResetFlagKeepParachutePackOnAfterTeleport = 222,
	CpedResetFlagDontRaiseFistsWhenLockedOn = 223,
	CpedResetFlagPreferMeleeBodyIkHitReaction = 224, // This will prefer all melee hit reactions to use body ik hit reactions if ragdoll is not selected
	CpedResetFlagProcessPhysicsTasksMotion = 225, // do we need to call process physics for motion tasks this frame
	CpedResetFlagProcessPhysicsTasksMovement = 226, // do we need to call process physics for movement tasks this frame
	CpedResetFlagDisableFriendlyGunReactAudio = 227, // If set, disables friendly responses to gunshots/being aimed at.
	CpedResetFlagDisableAgitationTriggers = 228,
	CpedResetFlagForceForwardTransitionInReactAndFlee = 229, // If set, force CTaskReactAndFlee to use a forward facing flee transition
	CpedResetFlagIsEnteringVehicle = 230, // TASK_ENTER_VEHICLE
	CpedResetFlagDoNotSkipNavMeshTrackerUpdate = 231, // If set we will not allow the NavMeshTracker update to be skipped this frame.
	CpedResetFlagRagdollOnVehicle = 232, // Set to true when the ragdoll is lying on top of a vehicle (note- hands, feet, forearms and shins are not included in the test)
	CpedResetFlagBlockRagdollActivationInVehicle = 233,
	CpedResetFlagDisableNmForRiverRapids = 234, // If set, disable NM reactions to fast moving water
	CpedResetFlagIsInWrithe = 235, // If set, the ped is on the ground writhing and might start shooting from ground
	CpedResetFlagPreventGoingIntoStillInVehicleState = 236, // If set, the ped will not go into the still in vehicle pose
	CpedResetFlagUseFastEnterExitVehicleRates = 237, // If set, the ped will get in and out of vehicles faster
	CpedResetFlagDisableGroundAttachment = 238, // If set, the ped won't attach to a ground physical when his physics disables (useful for cutscenes, etc)
	CpedResetFlagDisableAgitation = 239,
	CpedResetFlagDisableTalk = 240,
	CpedResetFlagInterruptedToQuickStartEngine = 241,
	CpedResetFlagPedEnteredFromLeftEntry = 242,
	CpedResetFlagIsDiving = 243,
	CpedResetFlagDisableVehicleImpacts = 244,
	CpedResetFlagDeepVehicleImpacts = 245,
	CpedResetFlagDisablePedCapsuleControl = 246,
	CpedResetFlagUseProbeSlopeStairsDetection = 247,
	CpedResetFlagDisableVehicleDamageReactions = 248,
	CpedResetFlagDisablePotentialBlastReactions = 249,
	CpedResetFlagOnlyAllowLeftArmDoorIk = 250,
	CpedResetFlagOnlyAllowRightArmDoorIk = 251,
	CpedResetFlagForceProcessPedStandingUpdateEachSimStep = 252, // When set, ProcessPedStanding will get called for each physics step.
	CpedResetFlagDisableFlashLight = 253, // When set, the flash light on a Ai weapon will be turned off.
	CpedResetFlagDoingCombatRoll = 254, // When set, the ped is doing a combat roll
	CpedResetFlagDisableBodyRecoilSolver = 255,
	CpedResetFlagCanAbortExitForInAirEvent = 256, // When set, the ped can abort the exit vehicle anim to go into fall
	CpedResetFlagDisableSprintDamage = 257,
	CpedResetFlagForceEnableFlashLightForAi = 258, // When set, the ai ped will enable their flash light
	CpedResetFlagIsDoingCoverAimIntro = 259,
	CpedResetFlagIsAimingFromCover = 260,
	CpedResetFlagWaitingForCompletedPathRequest = 261, // This ped is waiting for a path request which is now complete, so their tasks must be updated this frame
	CpedResetFlagDisableCombatAudio = 262,
	CpedResetFlagDisableCoverAudio = 263,
	CpedResetFlagPreventBikeFromLeaning = 264,
	CpedResetFlagInCoverTaskActive = 265,
	CpedResetFlagEnableSteepSlopePrevention = 266, // Pushes the ped through the same steep slope tolerances in TaskMotionBase that the player encounters
	CpedResetFlagInsideEnclosedSearchRegion = 267,
	CpedResetFlagJumpingOutOfVehicle = 268,
	CpedResetFlagIsTuckedOnBicycleThisFrame = 269,
	CpedResetFlagProcessPostMovementTimeSliced = 270, // Parallel flag to ProcessPostMovement, except this is reset in PreTask(), meaning it stays consistent across timeslicing.
	CpedResetFlagEnablePressAndReleaseDives = 271,
	CpedResetFlagOnlyExitVehicleOnButtonRelease = 272,
	CpedResetFlagIsGoingToStandOnExitedVehicle = 273,
	CpedResetFlagBlockRagdollFromVehicleFallOff = 274,
	CpedResetFlagDisableTorsoVehicleSolver = 275,
	CpedResetFlagIsExitingUpsideDownVehicle = 276,
	CpedResetFlagIsExitingOnsideVehicle = 277,
	CpedResetFlagIsExactStopping = 278,
	CpedResetFlagIsExactStopSettling = 279,
	CpedResetFlagIsTrainCrushingRagdoll = 280,
	CpedResetFlagOverrideHairScale = 281, // Scales the ped's hair down to the specified value
	CpedResetFlagConsiderAsPlayerCoverThreatWithoutLos = 282, // Considered as a threat as part of player cover search even if they can't see the player
	CpedResetFlagBlockCustomAiEntryAnims = 283,
	CpedResetFlagIgnoreVehicleEntryCollisionTests = 284,
	CpedResetFlagStreamActionModeAnimsIfDisabled = 285, // Stream action mode anims even if action mode is disabled
	CpedResetFlagForceUpdateRagdollMatrix = 286, // Ped requires ragdoll matrix update next frame.
	CpedResetFlagPreventGoingIntoShuntInVehicleState = 287, // If set, the ped will not go into the shunt in vehicle pose
	CpedResetFlagDisableIndependentMoverFrame = 288,
	CpedResetFlagDoingDrivebyOutro = 289,
	CpedResetFlagBeingElectrocuted = 290,
	CpedResetFlagDisableUnarmedDrivebys = 291,
	CpedResetFlagTalkingToPlayer = 292,
	CpedResetFlagDontActivateRagdollFromPlayerPedImpactReset = 293, // Block ragdoll activations from animated player bumps
	CpedResetFlagDontActivateRagdollFromAiRagdollImpactReset = 294, // Block ragdoll activations from collisions with an ai ragdoll
	CpedResetFlagDontActivateRagdollFromPlayerRagdollImpactReset = 295, // Block ragdoll activations from collisions with a player ragdoll
	CpedResetFlagDisableVisemeBodyAdditive = 296, // If set, prevents visemes from playing any additive body animations
	CpedResetFlagCapsuleBeingPushedByPlayerCapsule = 297, // Set when the player capsule is pushing up against this peds capsule
	CpedResetFlagForceActionMode = 298,
	CpedResetFlagForceUnarmedActionMode = 299,
	CpedResetFlagUsingMoverExtraction = 300, // Set when the players capsule is getting repositioned each frame relative to an anim and origin
	CpedResetFlagBeingJacked = 301,
	CpedResetFlagEnableVoiceDrivenMouthMovement = 302, // If set, turn on the voice driven mouth movement
	CpedResetFlagIsReloading = 303,
	CpedResetFlagUseTighterEnterVehicleSettings = 304, // Ped should use tighter (shorter) settings for entering vehicles
	CpedResetFlagInRaceMode = 305, // Set when the player is in the race mode.
	CpedResetFlagDisableAmbientMeleeMoves = 306, // Disable ambient (initial) melee moves
	CpedResetFlagForceBuoyancyProcessingIfAsleep = 307,
	CpedResetFlagAllowSpecialAbilityInVehicle = 308, // Allows the player to trigger the special ability while in a vehicle
	CpedResetFlagDisableInVehicleActions = 309, // Prevents ped from doing in vehicle actions such as starting engine, hotwiring, closing door etc.
	CpedResetFlagForceInstantSteeringWheelIkBlendIn = 310, // Forces ped to blend in steering wheel ik instantly rather than over time.
	CpedResetFlagIgnoreThreatEngagePlayerCoverBonus = 311, // Ignores the bonus score for selecting cover that the player can engage the enemy at
	CpedResetFlagBlock180Turns = 312, // Blocks triggering of 180 turns in human locomotion this frame.
	CpedResetFlagDontCloseVehicleDoor = 313, // Prevents the ped from closing the vehicle door of the car they're in
	CpedResetFlagSkipExplosionOcclusion = 314, // Map collision will not block this ped from being hit by explosions
	CpedResetFlagProcessPhysicsTasksTimeSliced = 315, // Parallel flag to ProcessPhysicsTasks, except this is reset in PreTask(), meaning it stays consistent across timeslicing.
	CpedResetFlagMeleeStrikeAgainstNonPed = 316, // Set when the ped has performed a melee strike and hit any non ped material
	CpedResetFlagIgnoreNavigationForDoorArmIk = 317, // We will not attempt to walk around doors when using arm IK
	CpedResetFlagDisableAimingWhileParachuting = 318, // Disable aiming while parachuting
	CpedResetFlagDisablePedCollisionWithPedEvent = 319, // Disable hit reaction due to colliding with a ped
	CpedResetFlagIgnoreVelocityWhenClosingVehicleDoor = 320, // Will ignore the vehicle speed threshold and close the door anyway
	CpedResetFlagSkipOnFootIdleIntro = 321,
	CpedResetFlagDontWalkRoundObjects = 322, // Don't walk round objects that we collide with whilst moving
	CpedResetFlagDisablePedEnteredMyVehicleEvents = 323,
	CpedResetFlagCancelLeftHandGripIk = 324, // Call ProcessLeftHandGripIk() to cancel left hand grip IK, at the right time of the frame
	CpedResetFlagResetMovementStaticCounter = 325, // Will keep reset the static counter when this is set
	CpedResetFlagDisableInVehiclePedVariationBlocking = 326, // Will allow ped variations to be rendered in vehicles, even if marked otherwise
	CpedResetFlagReduceEffectOfVehicleRamControlLoss = 327, // When on a mission this reset flag will slightly reduce the amount of time the player loses control of their vehicle when hit by an AI ped
	CpedResetFlagDisablePlayerMeleeFriendlyAttacks = 328, // Another flag to disable friendly attack from the player. Set on the opponent you would like it to be disabled on.
	CpedResetFlagMotionPedDoPostMovementIndependentMover = 329,
	CpedResetFlagIsMeleeTargetUnreachable = 330, // Set when the melee target has been deemed unreachable (AI only)
	CpedResetFlagDisableAutoForceOutWhenBlowingUpCar = 331,
	CpedResetFlagThrowingProjectile = 332,
	CpedResetFlagOverrideHairScaleLarger = 333, // Scales the ped's hair up to the specified value
	CpedResetFlagDisableDustOffAnims = 334, // Disable amient dust off animations
	CpedResetFlagDisableMeleeHitReactions = 335, // This ped will refrain from ever performing a melee hit reaction
	CpedResetFlagVisemeAnimsAudioBlocked = 336, // Blocks viseme anims audio from playing
	CpedResetFlagAllowHeadPropInVehicle = 337, // This overrides PV_FLAG_NOT_IN_CAR set on any head prop and stops it from being removed when getting into the vehicle
	CpedResetFlagIsInVehicleChase = 338,
	CpedResetFlagDontQuitMotionAiming = 339,
	CpedResetFlagSetLastBoundMatricesDone = 340, // Ensure that the last bound matrices are only updated once per frame
	CpedResetFlagPreserveAnimatedAngularVelocity = 341, // Don't allow the locomotion task to adjust angular velocity coming from animation
	CpedResetFlagOpenDoorArmIk = 342, // Set if the ped should enable open door arm IK
	CpedResetFlagUseTighterTurnSettingsForScript = 343, // Script set flag, to force use of tighter turn settings in locomotion task
	CpedResetFlagForcePreCameraProcessExternallyDrivenDoFs = 344, // Set if the ped should process externally driven dofs before the pre-camera ai update
	CpedResetFlagLadderBlockingMovement = 345, // Ped is waiting for ladder and blocking movement to prevent falling off
	CpedResetFlagDisableVoiceDrivenMouthMovement = 346, // If set, turn off the voice driven mouth movement (overrides EnableVoiceDrivenMouthMovement)
	CpedResetFlagSteerIntoSkids = 347, // If set, steer into skids while driving
	CpedResetFlagAllowOpenDoorIkBeforeFullMovement = 348, // When set, code will ignore the logic that requires the ped to be in CTaskHumanLocomotion
	CpedResetFlagAllowHomingMissileLockOnInVehicle = 349, // When set, code will bypass rel settings and allow a homing lock on to this ped when they are in a vehicle
	CpedResetFlagAllowCloneForcePostCameraAiUpdate = 350,
	CpedResetFlagDisableHighHeels = 351, // Force the high heels DOF to be 0
	CpedResetFlagBreakTargetLock = 352, // Force lock on to break for this ped
	CpedResetFlagDontUseSprintEnergy = 353, // Player does not get tired when sprinting
	CpedResetFlagDontChangeHorseMbr = 354, // Similar to CPED_RESET_FLAG_DontChangeMbrInSimpleMoveDoNothing, but for horses.
	CpedResetFlagDisableMaterialCollisionDamage = 355, // Don't be damaged by touching dangerous material (e.g. electic generator)
	CpedResetFlagDisableMpFriendlyLockon = 356, // Don't target friendly players in MP
	CpedResetFlagDisableMpFriendlyLethalMeleeActions = 357, // Don't melee kill friendly players in MP
	CpedResetFlagIfLeaderStopsSeekCover = 358, // If our leader stops, try and seek cover if we can
	CpedResetFlagProcessPostPreRenderAfterAttachments = 359, // do we need to call CPED_RESET_FLAG_ProcessPostPreRenderAfterAttachments for tasks
	CpedResetFlagDoDamageCoughFacial = 360,
	CpedResetFlagIsUsingJetpack = 361, // Is ped currently using jetpack. e.g. in air
	CpedResetFlagUseInteriorCapsuleSettings = 362, // Use Interior capsule settings
	CpedResetFlagIsClosingVehicleDoor = 363, // Ped is closing a vehicle door
	CpedResetFlagDisableIdleExtraHeadingChange = 364, // Disable lerping the ped towards the desired heading in the locomotion idle
	CpedResetFlagOnlySelectVehicleWeapons = 365, // Only allows vehicle weapons to be selected in CPedWeaponSelector
	CpedResetFlagIsWarpingIntoVehicleMp = 366, // Set in CTaskEnterVehicle
	CpedResetFlagRemoveHelmet = 367, // Forces a ped to remove its helmet.
	CpedResetFlagIsRemovingHelmet = 368, // Returns true if ped is removing its helmet.
	CpedResetFlagGestureAnimsBlockedFromScript = 369,
	CpedResetFlagNeverRagdoll = 370, // Disable all attempts by this ped to ragdoll.
	CpedResetFlagDisableWallHitAnimation = 371, // Disable stuck wall hit animation for the ped this frame.
	CpedResetFlagPlayAgitatedAnimsInVehicle = 372, // Play agitated anims in vehicle - overrides normal sit idle
	CpedResetFlagIsSeatShuffling = 373, // Returns true if ped is shuffling seat.
	CpedResetFlagIsThrowingProjectileWhileAiming = 374, // True if we are running TASK_AIM_AND_THROW_PROJECTILE as a subtask of TASK_AIM_GUN_ON_FOOT.
	CpedResetFlagDisableProjectileThrowsWhileAimingGun = 375, // Set by script command DISABLE_PLAYER_THROW_GRENADE_WHILE_USING_GUN.
	CpedResetFlagAllowControlRadioInAnySeatInMp = 376, // Allows ped in any seat to control radio in multiplayer.
	CpedResetFlagDisableSpycarTransformation = 377, // Blocks ped from manually transforming spycar to/from car/sub modes.
	CpedResetFlagBlockQuadLocomotionIdleTurns = 378, // Prevent CTaskQuadLocomotion from blending in idle turns, regardless of desired/currenting heading differential.
	CpedResetFlagBlockHeadbobbingToRadio = 379, // Blocks ped from headbobbing to radio music in vehicles.
	CpedResetFlagPlayFpsIdleFidgets = 380, // Allows us to load and play idle fidgets in TaskMotionAiming
	CpedResetFlagForceExtraLongBlendInForPedSkipIdleCoverTransition = 381, // When putting a ped directly into cover, the ped will blend in the new cover anims slowly to prevent a pose pop
	CpedResetFlagBlendingOutFpsIdleFidgets = 382, // True if FPS idle fidgets are blending out
	CpedResetFlagDisableMotionBaseVelocityOverride = 383,
	CpedResetFlagFpsSwimUseSwimMotionTask = 384, // Set to true when we are pressing forward on the left stick in FPS mode so we switch from Aiming to Swimmimg/Diving motion tasks
	CpedResetFlagFpsSwimUseAimingMotionTask = 385, // Set to true when we are strafing in water in FPS mode so we use the motion aiming task
	CpedResetFlagFiringWeaponWhenReady = 386, // set when ped has decided to fire weapon when ready, used in FPS mode
	CpedResetFlagIsBlindFiring = 387, // True if the blind fire task is running
	CpedResetFlagIsPeekingFromCover = 388, // True if the ped is peeking in cover
	CpedResetFlagTaskSkipProcessPreComputeImpacts = 389, // True to bail out of ProcessPreComputeImpacts
	CpedResetFlagDisableAssistedAimLockon = 390, // Don't ever try to lock on to this ped with cinematic aim
	CpedResetFlagFpsAllowAimIkForThrownProjectile = 391, // To control enabling of FPS aim IK while using a projectile until it is ready
	CpedResetFlagTriggerRoadRageAnim = 392,
	CpedResetFlagForcePreCameraAiAnimUpdateIfFirstPerson = 393, // Force a pre camera ai and animation update if the ped is the first person camera target during the pre camera update
	CpedResetFlagNoCollisionDamageFromOtherPeds = 394, // Any ped this is set on won't register damage from collisions against other peds.
	CpedResetFlagBlockCameraSwitching = 395, // Block camera view mode switching.
	CpedResetFlagNeverDieFromCapsuleRagdollSettings = 396, // Negate the capsule's preference for ragdoll triggering death on this ped.
	CpedResetFlagInContactWithDeepSurface = 397, // ped is in contact with GTA_DEEP_SURFACE_TYPE bounds
	CpedResetFlagDontSuppressUseNavMeshToNavigateToVehicleDoorWhenVehicleInWater = 398,
	CpedResetFlagIncludePedReferenceVelocityWhenFiringProjectiles = 399, // Add on the ped's velocity to the projectile's initial velocity.
	CpedResetFlagIsDoingCoverOutroToPeek = 400,
	CpedResetFlagInstantBlendToAimNoSettle = 401,
	CpedResetFlagForcePreCameraAnimUpdate = 402, // Force a pre camera animation update if the ped is the first person camera target during the pre camera update
	CpedResetFlagDisableHelmetCullFps = 403, // Disables PV_FLAG_HIDE_IN_FIRST_PERSON from culling the prop in CPedPropsMgr
	CpedResetFlagShouldIgnoreCoverAutoHeadingCorrection = 404,
	CpedResetFlagDisableReticuleInCoverThisFrame = 405,
	CpedResetFlagForceScriptedCameraLowCoverAngleWhenEnteringCover = 406,
	CpedResetFlagDisableCameraConstraintFallBackThisFrame = 407,
	CpedResetFlagDisableFpsArmIk = 408, // Disables FPS arm IK in CTaskPlayerOnFoot
	CpedResetFlagDisableRightArmIkInCoverOutroFps = 409, // Turn off right arm IK during cover outros in FPS mode when set
	CpedResetFlagDoFpsSprintBreakOut = 410,
	CpedResetFlagDoFpsJumpBreakOut = 411,
	CpedResetFlagIsExitingCover = 412,
	CpedResetFlagWeaponBlockedInFpsMode = 413, // True if running CTaskWeaponBlocked in FPS mode
	CpedResetFlagPoVCameraConstrained = 414,
	CpedResetFlagScriptClearingPedTasks = 415, // Set in CommandClearPedTasksImmediately in commands_task.cpp
	CpedResetFlagWasFpsJumpingWithProjectile = 416, // ped was jumping on foot with projectile in hand
	CpedResetFlagDisableMeleeWeaponSelection = 417,
	CpedResetFlagWaypointPlaybackSlowMoreForCorners = 418, // slow for corners more aggressively for waypoint playback
	CpedResetFlagFpsPlacingProjectile = 419, // True while placing a projectile in FPS mode
	CpedResetFlagUseBulletPenetrationForGlass = 420, // Ped will use bullet penetration code when glass material is hit.
	CpedResetFlagFpsPlantingBombOnFloor = 421, // Doing a floor plant with a bomb in FPS mode
	CpedResetFlagForceSkipFpsAimIntro = 422, // don't do FPS Aim intro
	CpedResetFlagCanBePinnedByFriendlyBullets = 423, // If set on a ped then they are allowed to be pinned by bullets from friendly peds
	CpedResetFlagDisableLeftArmIkInCoverOutroFps = 424, // Turn off left arm IK during cover outros in FPS mode when set
	CpedResetFlagDisableSpikeStripRoadBlocks = 425, // Blocks road blocks with spike strips from spawning
	CpedResetFlagSkipFpsUnHolsterTransition = 426, // skip aim unholster transition
	CpedResetFlagPutDownHelmetFx = 427, // trigger the put down helmet fx
	CpedResetFlagIsLowerPriorityMeleeTarget = 428, // Peds marked with this flag will only be able to be hit by the player if the player explicitly presses the melee button
	CpedResetFlagForceScanForEventsThisFrame = 429, // disable timeslicing of event scanning
	CpedResetFlagStartProjectileTaskWithPrimingDisabled = 430, // Set this flag to disable priming when the projectile task starts up until the attack trigger is released and pressed again
	CpedResetFlagCheckFpsSwitchInCameraUpdate = 431, // Set if we want to perform a second AI/anim update when switching between first person/third person
	CpedResetFlagForceAutoEquipHelmetsInAicraft = 432, // Force ped to auto-equip a helmet om entering aircraft. Overrides PCF_DisableAutoEquipHelmetsInAicraft (set in the interaction menu)
	CpedResetFlagBlockRemotePlayerRecording = 433, // Flag used by replay editor to disable recording specified remote players (for url
	CpedResetFlagInflictedDamageThisFrame = 434, // Inflicted damage this frame
	CpedResetFlagUseFirstPersonVehicleAnimsIfFpsCamNotDominant = 435, // allow FPS vehicle anims even if FPS camera isn't dominant
	CpedResetFlagForceIntoStandPoseOnJetski = 436, // puts the ped in a standing pose on the jetski
	CpedResetFlagInAirDefenceSphere = 437, // Ped is located inside an air defence sphere.
	CpedResetFlagSuppressTakedownMeleeActions = 438, // This will suppress all takedown melee actions (RA_IS_TAKEDOWN or RA_IS_STEALTH_KILL, defined in action_table.meta)
	CpedResetFlagInvertLookAroundControls = 439, // Inverts lookaround controls (right stick / mouse) for this player, for this frame.
	CpedResetFlagIgnoreCombatManager = 440, // Allows attacking ped to engage another entity without waiting for its turn (if there's multiple attackers).
	CpedResetFlagUseBlendedCamerasOnUpdateFpsCameraRelativeMatrix = 441, // Check if there is an active camera blending and use the blended camera frame when compute the FPS camera relative matrix.
	CpedResetFlagForceMeleeCounter = 442, // Forces the ped to perform a dodge and a counter move if it's attacked.
	CpedResetFlagWasHitByVehicleMelee = 443, // Indicates that ped was hit by vehicle melee attack.
	CpedResetFlagSuppressNavmeshForEnterVehicleTask = 444, // Dont allow ped to use navmesh when navigating in TaskEnterVehicle
	CpedResetFlagDisableShallowWaterBikeJumpOutThisFrame = 445,
	CpedResetFlagDisablePlayerCombatRoll = 446, // Disables player combat rolling.
	CpedResetFlagIgnoreDetachSafePositionCheck = 447, // Will ignore safe position check on detaching the ped
	CpedResetFlagDisableEasyLadderConditions = 448, // Prevents the more forgiving MP ladder detection settings from being used, and forces SP settings.
	CpedResetFlagPlayerIgnoresScenarioSpawnRestrictions = 449, // Makes local player ignore certain scenario spawn restrictions on scenarios that respect this flag
	CpedResetFlagUsingDrone = 450, // Indicates player is using Drone from Battle DLC
	CpedResetFlagForceWantedLevelWhenKilled = 451, // Will force the player that killed this ped to get wanted level, even if he wouldnt otherwise
	CpedResetFlagUseScriptedWeaponFirePosition = 452, // Will use scripted firing position on the clones of this ped on other machines
	CpedResetFlagEnableCollisionOnNetworkCloneWhenFixed = 453, // Enable collision on player ped network clones when physics is fixed
	CpedResetFlagUseExtendedRagdollCollisionCalculator = 454, // Use extended logic for determining damage instigator for ragdoll collisions
	CpedResetFlagPreventLockonToFriendlyPlayers = 455, // Prevent the player locking on to friendly players
	CpedResetFlagOnlyAbortScriptedAnimOnMovementByInput = 456, // Modifies AF_ABORT_ON_PED_MOVEMENT to only trigger an abort when movement would be caused by player input
	CpedResetFlagPreventAllStealthKills = 457, // Prevents stealth take downs from being preformed on a ped
	CpedResetFlagBlockFallTaskFromExplosionDamage = 458, // Prevent peds from entering a fall task if affected by explosion damage
	CpedResetFlagAllowPedRearEntry = 459, // Mimics the behaviour like with boss peds by holding the button for entering the rear seats*
}