export enum ERayFireMapObjectState {
	RfmoStateInvalid = -1,
	RfmoStateInit,
	RfmoStateSyncStarting,
	RfmoStateStarting,
	RfmoStateStart,
	RfmoStatePriming,
	RfmoStatePrimed,
	RfmoStateStartAnim,
	RfmoStateAnimating,
	RfmoStateSyncEnding,
	RfmoStateEnding,
	RfmoStateEnd,
	RfmoStateReset,
	RfmoStatePause,
	RfmoStateResume,
	RfmoStatePrimingPrelude,
	RfmoStateAbandon,
}