export enum ESellingVehicleType {
	SvtEarnFromVehicle,
	SvtEarnFromPersonalNormalVehicle,
	SvtEarnFromPersonalHighendVehicle,
	SvtEarnFromPersonalWeaponVehicle,
	SvtEarnFromPersonalAircraftVehicle,
	SvtEarnFromH2WeaponizedVehicle,
	SvtEarnFromBattlesWeaponizedVehicle,
}