export enum ESpecialAbilityType {
	SatInvalid = -1,
	SatCarSlowdown,
	SatRage,
	SatBulletTime,
	SatSnapshot,
	SatInsult,
	SatArcadeEnraged,
	SatArcadeGhost,
	SatArcadeSprintSpeedBoost,
	SatArcadeNitroCop,
	SatArcadeNitroCrook,
	SatArcadeEmp,
	SatArcadeSpikeMine,
	SatArcadeFullThrottle,
	SatArcadePumpedUp,
	SatArcadeBackup,
	SatArcadeOilSlick,
	SatArcadeKineticRam,
}