export enum EStatsDisplayType {
	StatTypeNone, // Invalid/not set type
	StatTypeInt, // Base types
	StatTypeFloat,
	StatTypeString,
	StatTypeBoolean,
	StatTypeDouble,
	StatTypeUint8,
	StatTypeUint16,
	StatTypeUint32,
	StatTypeUint64,
	StatTypeTime,
	StatTypeCash,
	StatTypePercent,
	StatTypeDegrees,
	StatTypeWeight,
	StatTypeMiles,
	StatTypeMeters,
	StatTypeFeet,
	StatTypeSeconds,
	StatTypeChart,
	StatTypeVelocity,
	StatTypeDate,
	StatTypePos,
	StatTypeTextlabel,
	StatTypePacked,
	StatTypeUserId,
	MaxStatType,
}