export enum ESwitchState {
	Intro,
	PrepDescent,
	PrepForCut,
	JumpcutAscent,
	WaitforinputIntro,
	Waitforinput,
	WaitforinputOutro,
	Pan,
	JumpcutDescent,
	OutroHold,
	OutroSwoop,
	EstablishingShot,
	Finished,
	Outro = 9,
}