export enum EUgcError {
	UnexpectedResult = -1,
	None,
	AuthenticationfailedTicket,
	DoesnotexistContent,
	DoesnotexistPublisher,
	InvalidargumentCloudabspath,
	InvalidargumentContentid,
	InvalidargumentContentname,
	InvalidargumentContenttype,
	InvalidargumentOnlineservice,
	InvalidargumentTags,
	InvalidargumentTitleinfo,
	InvalidargumentUserid,
	NotallowedMaxcreated,
	NotallowedNotcontentowner,
	NotallowedNotlatest,
	NotallowedProfane,
	NotallowedReservedword,
	OutofrangeContenttype,
}