export enum EWeatherType {
	WeatherExtrasunny,
	WeatherClear,
	WeatherClouds,
	WeatherSmog,
	WeatherCloudy,
	WeatherOvercast,
	WeatherRain,
	WeatherThunder,
	WeatherClearing,
	WeatherNeutral,
	WeatherSnowlight,
	WeatherSnow,
	WeatherBlizzard,
}